### ISSUE TITLE
Cannot run Tardis Example after re-installation

### ISSUE THREAD

**Issue by manolis07gr** [tardis-sn/tardis#1807]
Dear TARDIS team,

I recently updated to the latest version of TARDIS using the conda3 environment as following the installation guidelines as recommended in your website to re-do the "Quickstart" run (https://tardis-sn.github.io/tardis/quickstart/quickstart.html). I am however unable to run this setup and I keep getting the following error after running sim = run_tardis('tardis_example.yml'):

Traceback (most recent call last):
  File "/Users/emmanouilchatzopoulos/Desktop/tardis/tardis/base.py", line 80, in run_tardis
    tardis_config = Configuration.from_yaml(config)
  File "/Users/emmanouilchatzopoulos/Desktop/tardis/tardis/io/config_reader.py", line 261, in from_yaml
    return cls.from_config_dict(yaml_dict, *args, **kwargs)
  File "/Users/emmanouilchatzopoulos/Desktop/tardis/tardis/io/config_reader.py", line 281, in from_config_dict
    validated_config_dict = config_validator.validate_dict(config_dict)
  File "/Users/emmanouilchatzopoulos/Desktop/tardis/tardis/io/config_validator.py", line 75, in validate_dict
    schema=schema, types={"quantity": (Quantity,)}, resolver=resolver
TypeError: __init__() got an unexpected keyword argument 'types'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/emmanouilchatzopoulos/Desktop/tardis/tardis/base.py", line 85, in run_tardis
    tardis_config = Configuration.from_config_dict(config)
  File "/Users/emmanouilchatzopoulos/Desktop/tardis/tardis/io/config_reader.py", line 281, in from_config_dict
    validated_config_dict = config_validator.validate_dict(config_dict)
  File "/Users/emmanouilchatzopoulos/Desktop/tardis/tardis/io/config_validator.py", line 75, in validate_dict
    schema=schema, types={"quantity": (Quantity,)}, resolver=resolver
TypeError: __init__() got an unexpected keyword argument 'types'

This happens regardless of running the script locally on my computer or using a Jupyter nootebook.

Any suggestions/ideas would be helpful.

Also - I am assuming this version of TARDIS includes the updates that were implemented to include physics important to calculating Type IIP supernova spectra as used in this paper (https://arxiv.org/pdf/1811.02543.pdf) correct? I am only asking as I am seeking to compute a Type IIP spectrum using STELLA data.

Best,

Manos

**Comment by andrewfullard** [comment]
This should be fixed after #1806 is merged.

**Comment by manolis07gr** [comment]
Hi @andrewfullard - I just checked out the latest update of the TARDIS git repo and the problem persists, am I still missing something?

Thanks,

Manos

**Comment by epassaro** [comment]
The patch @andrewfullard mentioned hasn't been merged yet. You can downgrade `jsonschema` in your environment if you need to get it working now.

**Comment by wkerzendorf** [comment]
I think, we need to fix this as python 3.8 is pretty old now and other environments will fail.

**Comment by epassaro** [comment]
> I think, we need to fix this as python 3.8 is pretty old now and other environments will fail.

@wkerzendorf Do you mean patch the TARDIS codebase to work with `jsonschema>3.2.0`?

**Comment by epassaro** [comment]
Closed by #2050
